CREATE TABLE STATIONARY_PRODUCTS(
ID INT,
PRODUCTS_NAME VARCHAR(10),
COST_PRICE INT);
INSERT INTO STATIONARY_PRODUCTS VALUES (1, 'PENCIL', 10);
INSERT INTO STATIONARY_PRODUCTS VALUES (2,'SHARPENER', 10);
INSERT INTO STATIONARY_PRODUCTS VALUES (3, 'CALCULATOR', 900);
SELECT * FROM STATIONARY_PRODUCTS WHERE COST_PRICE > 100;